# Generated by Django 4.1.3 on 2022-11-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pesel',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
