# Generated by Django 4.1.3 on 2023-01-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchaseditcketslist',
            name='days_quantity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpurchaseditcketslist',
            name='lines',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='userpurchaseditcketslist',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
