# Generated by Django 4.1.3 on 2022-11-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_pesel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pesel',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
