# Generated by Django 4.1.3 on 2023-01-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userpurchaseditcketslist_days_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='funds',
            field=models.SmallIntegerField(default=0),
        ),
    ]
