# Generated by Django 4.1.3 on 2023-01-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchaseditcketslist',
            name='days_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
