# Generated by Django 4.1.3 on 2023-01-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_userpurchaseditcketslist_valid_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpurchaseditcketslist',
            old_name='ticket_id',
            new_name='ticket',
        ),
    ]
