# Generated by Django 4.1.3 on 2023-01-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_userpurchaseditcketslist_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpurchaseditcketslist',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='userpurchaseditcketslist',
            name='user',
        ),
        migrations.AddField(
            model_name='userpurchaseditcketslist',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
