# Generated by Django 4.1.3 on 2023-01-17 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_userpurchaseditcketslist_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpurchaseditcketslist',
            name='type',
        ),
    ]
